---
jenkins:
  systemMessage: "Jenkins — hands-on-satubinha | Gerido por JCasC"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_USER}"
          password: "${JENKINS_ADMIN_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  remotingSecurity:
    enabled: true
unclassified:
  location:
    url: "http://${JENKINS_PUBLIC_IP}:8080/"
    adminAddress: "admin@satubinha.lab"
  timestamper:
    allPipelines: true
  ansiColorBuildWrapper:
    globalColorMapName: "xterm"
jobs:
  - script: |
      pipelineJob('satubinha-foundation') {
        description('Layer foundation — network + security-group | dev')
        keepDependencies(false)
        properties {
          githubProjectUrl('https://github.com/fabricio-f5/hands-on-satubinha-iac-terragrunt/')
          buildDiscarder {
            strategy {
              logRotator {
                daysToKeepStr('')
                numToKeepStr('10')
                artifactDaysToKeepStr('')
                artifactNumToKeepStr('')
              }
            }
          }
        }
        triggers {
          githubPush()
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/fabricio-f5/hands-on-satubinha-jenkins.git')
                }
                branches('*/master')
                extensions {}
              }
            }
            scriptPath('pipelines/Jenkinsfile.foundation')
            lightweight(true)
          }
        }
      }
  - script: |
      pipelineJob('satubinha-ec2') {
        description('Layer ec2 | dev — depende da layer foundation')
        keepDependencies(false)
        properties {
          githubProjectUrl('https://github.com/fabricio-f5/hands-on-satubinha-iac-terragrunt/')
          buildDiscarder {
            strategy {
              logRotator {
                daysToKeepStr('')
                numToKeepStr('10')
                artifactDaysToKeepStr('')
                artifactNumToKeepStr('')
              }
            }
          }
        }
        triggers {
          githubPush()
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/fabricio-f5/hands-on-satubinha-jenkins.git')
                }
                branches('*/master')
                extensions {}
              }
            }
            scriptPath('pipelines/Jenkinsfile.ec2')
            lightweight(true)
          }
        }
      }
